name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm # ← AJOUT : installe pnpm avant Node
        uses: pnpm/action-setup@v4
        with:
          version: 10.27.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm" # ← était "npm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile # ← était "npm ci"

      - name: Build
        run: pnpm run build # ← était "npm run build"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL}}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY}}
